version: '3.7'

services:
  postgres:
    image: postgres:11.5-alpine
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authDB

volumes:
  database: